version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:40"
    volumes:
      - ./nginx.conf:/Users/zirnsack/Downloads/game.server 2/server/nginx.conf
      - ./static:/Users/zirnsack/Downloads/game.server 2/src/main/java/lws/GameResultApplication/frontend/*.html
      - ./logs:/Users/zirnsack/Downloads/game.server 2/server/logs/nginx

volumes:
  local_pgdata:
